bootdo:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    root: info
    com.winchampion: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.25.185:3309/liwei_bootdo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #username: xyd-manager
    #password: xyd-manager
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    #host: 192.168.25.185
    #port: 6378
    #password: wc123456
    host: 127.0.0.1
    port: 6379
    password: test123
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
Country:
  appId: 39997c94e1d247e0a3cc28900b46f58d
  appKey: 39997c94e1d247e0a3cc28900b46f58d1589869978769
  appSecret: 8Xx3duQliPsX1DEyph2K4ijlRfrtKr9usmSJFemacV9zNXPGQ3FZAGCbrwlUARayfkV7wR2MV0617dI390pvbw==
  pullPublicKeyUrl: http://27.154.58.146:6589/api/pullPublicKey
  getTokenUrl: http://27.154.58.146:6589/api/getToken
  statisticsAllUrl: http://27.154.58.146:6589/api/qydkxx/financingStatisticsByAll
  statisticsDayUrl: http://27.154.58.146:6589/api/qydkxx/financingStatisticsByDay
Upload:
  templateName: 模板文件
  #uploadPath: D:\upload\template
  uploadPath: /Users/wanglichao/文件/